---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock

environment:
    DOCKER_BUILDKIT: '1'
    DOCKER_CONFIG: /drone/src/.docker

steps:
    - &docker
        name: docker login
        image: docker:20.10.1
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        environment:
            DOCKER_USERNAME:
                from_secret: docker_username
            DOCKER_PASSWORD:
                from_secret: docker_password

    - &builder
        <<: *docker
        name: docker
        commands:
            - docker build -t "automagistre/$DRONE_STEP_NAME:stable" --progress=plain --target "$DRONE_STEP_NAME" .
            - docker push "automagistre/$DRONE_STEP_NAME:stable"
        depends_on:
            - docker login

    -   <<: *builder
        name: git

    -   <<: *builder
        name: wait-for-it

    -   <<: *builder
        name: docker-compose

    -   <<: *builder
        name: github-cli
