---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock

environment:
    DOCKER_BUILDKIT: '1'
    DOCKER_CONFIG: /drone/src/.docker

steps:
    -   name: build and push
        image: automagistre/docker:stable
        pull: if-not-exists
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - |
                for image in $(grep -ioP 'FROM .+ AS \K.+' Dockerfile) ; do
                    docker build -t "automagistre/$image:stable" --progress=plain --target $image .
                    docker push "automagistre/$image:stable"
                done
        environment:
            DOCKER_USERNAME:
                from_secret: docker_username
            DOCKER_PASSWORD:
                from_secret: docker_password
